# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afa89d68c1706c5c4a774d1f3ef7b5527a3f3a2645ac3f339be1a53e37d7d3074f768ced8e76965a6ed6c71f9b97ad68487511dfeb9c219ce5865009795baf57

test:
  secret_key_base: 3c09e76f12cc6b7af5bd2dff89b8f84c0bb7e9539f2319ba6108f1da5648fafd953ec9bc52f034c932a8725bef3224289f0fdba60c41bfca5975b67cf91d5d47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
